### ISSUE TITLE
bump gulp-sass from 2.0.1 to 2.0.3 in generated repos

### ISSUE THREAD

**Issue by Ijmir** [mcfly-io/generator-sublime#249]

**Comment by jskrzypek** [comment]
This was fixed in https://github.com/mcfly-io/generator-sublime/pull/235

**Comment by jskrzypek** [comment]
Or it should have been

**Comment by jskrzypek** [comment]
https://github.com/mcfly-io/generator-sublime/blob/master/gulps/index.js#L93

**Comment by jskrzypek** [comment]
I'm sorry @Ijmir
