### ISSUE TITLE
Use gulp-watch instead of gulp.watch

### ISSUE THREAD

**Issue by thaiat** [mcfly-io/generator-sublime#261]
gulp.watch won't detect any new files in new folders

**Comment by jskrzypek** [comment]
It looks like gulp-watch adds it's own set of issues to the mix and the api for chokidar that it's built on top of is very simple. Perhaps we should just use the underlying chokidar? 

This has the added benefit of being in line with the planned implementation of gulp.watch in gulp v4 which is supposed to just be a simple wrapper for chokidar.

**Comment by jskrzypek** [comment]
Using chokidar directly also seems like an easy pattern for us since the src files we want to watch are all in separate folders so we can easily just rely on the 'all' events chokidar emits.

**Comment by thaiat** [comment]
will use browsersync watch function which is a wrapper around chokidar
that way we don't need to install another npm module
example of code:
```js
var taskStyleWatch = function(constants, done) {
    //gulp.watch(constants.style.watchFolder, ['style:nofont']);
    var bs = require('browser-sync').create();
    bs.watch(constants.style.watchFolder, function() {
        gulp.start('style:nofont', done);
    });
};
```
